import {NodoMM} from "../tree/NodoMM";
import {Expresion} from "../tree/Expresion";
import {Relacional} from "../tree/Relacional";
import {Condicional} from "../tree/Condicional";
import {Imprimir} from "../tree/Imprimir";
import {GraficarTS} from "../tree/GraficarTS";
import {Sentencias} from "../tree/Sentencias";
import {Declaracion} from "../tree/Declaracion";
import {DeclaFuncion} from "../tree/DeclaFuncion";
import {Recursivo} from "../tree/Recursivo";
import {Asignacion} from "../tree/Asignacion";
import {ExpArrayNew} from "../tree/ExpArrayNew";
import {ExpArray} from "../tree/ExpArray";
import {ExpLlamadaFuncion} from "../tree/ExpLlamadaFuncion";
import {DefObj} from "../tree/DefObj";
import {ExpObjeto } from "../tree/ExpObjeto";
import {SentIF} from "../tree/SentIF";
import {SentWHILE} from "../tree/SentWHILE";
import {SentDO} from "../tree/SentDO";
import {SentSWITCH} from "../tree/SentSWITCH";
import {SentFOR} from "../tree/SentFOR";
import {SentBREAK} from "../tree/SentBREAK";
import {SentCONTINUE} from "../tree/SentCONTINUE";
import {SentRETURN} from "../tree/SentRETURN";
import {ExpTernario} from "../tree/ExpTernario";
import { plantillaError } from "../utilities/plantillaError";/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var ejecutor = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,31],$V1=[1,32],$V2=[1,33],$V3=[1,20],$V4=[1,34],$V5=[1,30],$V6=[1,37],$V7=[1,28],$V8=[1,29],$V9=[1,38],$Va=[1,35],$Vb=[1,36],$Vc=[1,26],$Vd=[1,21],$Ve=[1,22],$Vf=[5,27,29,30,31,33,45,51,54,57,58,61,64,65,69,84,86],$Vg=[5,27,29,30,31,33,45,48,50,51,54,57,58,61,64,65,69,84,86],$Vh=[1,44],$Vi=[1,46],$Vj=[1,47],$Vk=[1,48],$Vl=[12,37],$Vm=[12,27,37,38,40,44,63,68,74,75,78,87,88,92,93,94,95,96,97,98,99,100,101,102,103],$Vn=[2,84],$Vo=[1,58],$Vp=[1,63],$Vq=[1,90],$Vr=[1,81],$Vs=[1,88],$Vt=[1,69],$Vu=[1,75],$Vv=[1,73],$Vw=[1,74],$Vx=[1,76],$Vy=[1,77],$Vz=[1,78],$VA=[1,79],$VB=[1,80],$VC=[1,89],$VD=[2,135],$VE=[12,27,37,38,40,44,63,87,88,92,93,94,95,96,97,98,99,100,101,102,103],$VF=[12,40],$VG=[1,106],$VH=[1,128],$VI=[1,126],$VJ=[1,127],$VK=[12,27,37,38,40,44,63,87,88],$VL=[1,136],$VM=[1,137],$VN=[1,138],$VO=[1,139],$VP=[1,140],$VQ=[1,141],$VR=[1,167],$VS=[37,40,63],$VT=[5,27,29,30,31,33,45,48,50,51,54,57,58,60,61,64,65,69,84,86],$VU=[27,29,30,31,45,48,50,51,54,57,58,61,64,65,69,84,86],$VV=[1,208],$VW=[37,40],$VX=[1,213],$VY=[12,27,37,38,40,44,62,63,68,74,75,78,87,88,92,93,94,95,96,97,98,99,100,101,102,103],$VZ=[12,27,37,38,40,44,63,87,88,92,93,94,95,96,97,98,99],$V_=[12,27,37,38,40,44,63,87,88,92,93,94,95,96,97,98,99,100,102],$V$=[1,240],$V01=[27,40],$V11=[1,256],$V21=[12,26,27,37,40,62,68],$V31=[48,50];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"INICIO":3,"SENTENCIASF":4,"EOF":5,"SENTENCIAF":6,"SENTENCIAS":7,"SENTENCIA":8,"DECLAFUNCION":9,"IMPRIMIR":10,"DECLARACION":11,"puntoycoma":12,"ASIGNACION":13,"LISTARECURSIVA":14,"DEFOBJETO":15,"SENTIF":16,"SENTWHILE":17,"SENTDO":18,"SENTFOR":19,"SENTBREAK":20,"SENTCONTINUE":21,"SENTRETURN":22,"SENTSWITCH":23,"LLAMADAFUNCION":24,"BLOQUESENT":25,"llaveabre":26,"llavecierra":27,"BLOQUESENTF":28,"break":29,"continue":30,"return":31,"COND":32,"function":33,"ID":34,"parentesisabre":35,"LISTAPARAMS":36,"parentesiscierra":37,"dospuntos":38,"LISTADIMS":39,"coma":40,"PARAM":41,"LISTAEXP":42,"TERNARIO":43,"pregunta":44,"switch":45,"BLOQUESWITCH":46,"LISTACASE":47,"default":48,"CASE":49,"case":50,"for":51,"FORINIT":52,"TIPOCAMBIO":53,"IDENTIFICADOR":54,"in":55,"of":56,"while":57,"do":58,"IF_LIST":59,"else":60,"if":61,"corcheteabre":62,"corchetecierra":63,"const":64,"let":65,"LISTADECLA":66,"DECLAELEMENT":67,"igual":68,"type":69,"LISTAATRIBUTOS":70,"EXPOBJ":71,"LISTAATRIBUTOSDEF":72,"INCREMENTOS":73,"masmas":74,"menosmenos":75,"ELEMENTRECURSIVO":76,"LISTAACCESODIMS":77,"punto":78,"length":79,"pop":80,"push":81,"toLowerCase":82,"toUpperCase":83,"console":84,"log":85,"graficar_ts":86,"and":87,"or":88,"not":89,"REL":90,"EXP":91,"mayor":92,"menor":93,"menoroigual":94,"mayoroigual":95,"igualigual":96,"diferente":97,"+":98,"-":99,"*":100,"potencia":101,"/":102,"%":103,"ENTERO":104,"DECIMAL":105,"CADENA":106,"verdadero":107,"falso":108,"null":109,"undefined":110,"EXPARRAY":111,"EXPARRAYNEW":112,"new":113,"Array":114,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",12:"puntoycoma",26:"llaveabre",27:"llavecierra",29:"break",30:"continue",31:"return",33:"function",35:"parentesisabre",37:"parentesiscierra",38:"dospuntos",40:"coma",44:"pregunta",45:"switch",48:"default",50:"case",51:"for",54:"IDENTIFICADOR",55:"in",56:"of",57:"while",58:"do",60:"else",61:"if",62:"corcheteabre",63:"corchetecierra",64:"const",65:"let",68:"igual",69:"type",74:"masmas",75:"menosmenos",78:"punto",79:"length",80:"pop",81:"push",82:"toLowerCase",83:"toUpperCase",84:"console",85:"log",86:"graficar_ts",87:"and",88:"or",89:"not",92:"mayor",93:"menor",94:"menoroigual",95:"mayoroigual",96:"igualigual",97:"diferente",98:"+",99:"-",100:"*",101:"potencia",102:"/",103:"%",104:"ENTERO",105:"DECIMAL",106:"CADENA",107:"verdadero",108:"falso",109:"null",110:"undefined",113:"new",114:"Array"},
productions_: [0,[3,2],[4,2],[4,1],[7,2],[7,1],[6,1],[6,1],[8,1],[8,2],[8,2],[8,2],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,2],[25,3],[25,2],[28,3],[20,2],[21,2],[22,2],[22,3],[9,9],[9,8],[9,6],[9,8],[9,7],[9,5],[36,3],[36,1],[41,3],[41,4],[24,4],[24,3],[43,5],[23,5],[46,6],[47,2],[47,1],[49,4],[19,9],[19,8],[19,8],[52,1],[52,1],[17,5],[18,7],[16,3],[16,1],[59,7],[59,5],[39,3],[39,2],[53,1],[53,1],[11,2],[66,3],[66,1],[67,6],[67,4],[67,5],[67,3],[67,3],[67,1],[15,7],[70,6],[70,5],[70,4],[70,3],[71,3],[72,5],[72,3],[13,3],[13,1],[73,2],[73,2],[14,2],[14,1],[14,2],[76,2],[76,3],[76,2],[76,4],[76,5],[76,4],[76,4],[77,4],[77,3],[10,7],[10,4],[32,3],[32,3],[32,2],[32,1],[32,1],[90,3],[90,3],[90,3],[90,3],[90,3],[90,3],[90,1],[91,3],[91,3],[91,3],[91,3],[91,3],[91,3],[91,1],[91,1],[91,2],[91,1],[91,1],[91,1],[91,1],[91,1],[91,3],[91,1],[91,1],[91,1],[91,1],[91,1],[91,1],[112,5],[111,3],[111,2],[42,3],[42,1],[34,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

            return $$[$0-1];
        
break;
case 2:

            $$[$0-1].hijos.push($$[$0]);
        
break;
case 3:

            this.$ = new Sentencias ("SENTENCIAS", "SENTENCIAS", _$[$0], [$$[$0]]);
        
break;
case 4: case 44:

            $$[$0-1].hijos.push($$[$0]);
            this.$ = $$[$0-1];
        
break;
case 5:

            this.$ = new Sentencias ("SENTENCIAS","SENTENCIAS",_$[$0] , [$$[$0]]);
        
break;
case 6: case 7: case 8: case 12: case 13: case 14: case 15: case 16: case 17: case 18: case 19: case 20: case 50: case 51: case 55: case 80: case 100: case 101: case 108: case 124: case 125: case 126: case 127: case 128: case 129:

            this.$ = $$[$0];
        
break;
case 9: case 10: case 11: case 21: case 22: case 24: case 76:

            this.$ = $$[$0-1];
        
break;
case 23:

           this.$ = new Sentencias ("SENTENCIAS","SENTENCIAS",[0,0], []);
        
break;
case 25:

            this.$ = new SentBREAK ("BREAK", "BREAK", _$[$0-1], []);
        
break;
case 26:

            this.$ = new SentCONTINUE ("CONTINUE", "CONTINUE", _$[$0-1], []);
        
break;
case 27:

            this.$ = new SentRETURN("RETURN", "RETURN", _$[$0-1], []);
        
break;
case 28:

            this.$ = new SentRETURN ("RETURN", "RETURN", _$[$0-2], [$$[$0-1]]);
        
break;
case 29:

            this.$ = new DeclaFuncion ("DECLAFUNCION", "DECLAFUNCION", _$[$0-7], [$$[$0-7], $$[$0-5], $$[$0-2], $$[$0-1], $$[$0]]);
        
break;
case 30:

            this.$ = new DeclaFuncion ("DECLAFUNCION", "DECLAFUNCION", _$[$0-6], [$$[$0-6], $$[$0-4], $$[$0-1], new NodoMM ("LISTADIMS", "LISTADIMS", _$[$0-7], 0), $$[$0]]);
        
break;
case 31:

            this.$ = new DeclaFuncion ("DECLAFUNCION", "DECLAFUNCION", _$[$0-4], [$$[$0-4], $$[$0-2], new NodoMM ("ID", "void", _$[$0-5], [] ) , new NodoMM ("LISTADIMS", "LISTADIMS", _$[$0-5], 0), $$[$0]]);
        
break;
case 32:

            this.$ = new DeclaFuncion ("DECLAFUNCION", "DECLAFUNCION", _$[$0-6], [$$[$0-6], new NodoMM ("LISTAPARAMS", "LISTAPARAMS", _$[$0-7], []), $$[$0-2], $$[$0-1], $$[$0]]);
        
break;
case 33:

            this.$ = new DeclaFuncion ("DECLAFUNCION", "DECLAFUNCION", _$[$0-5], [$$[$0-5], new NodoMM ("LISTAPARAMS", "LISTAPARAMS", _$[$0-6], []), $$[$0-1], new NodoMM ("LISTADIMS", "LISTADIMS", _$[$0-6], 0), $$[$0]]);
        
break;
case 34:

            this.$ = new DeclaFuncion ("DECLAFUNCION", "DECLAFUNCION", _$[$0-3], [$$[$0-3], new NodoMM ("LISTAPARAMS", "LISTAPARAMS", _$[$0-4], []), new NodoMM ("ID", "void", _$[$0-4], [] ), new NodoMM ("LISTADIMS", "LISTADIMS", _$[$0-4], 0), $$[$0]]);
        
break;
case 35: case 63: case 133:

            $$[$0-2].hijos.push($$[$0]);
            this.$ = $$[$0-2];
        
break;
case 36:


            this.$ = new NodoMM ("LISTAPARAMS", "LISTAPARAMS", _$[$0], [$$[$0]]);
        
break;
case 37:

            this.$ = new NodoMM ("PARAM", "PARAM", _$[$0-1], [$$[$0-2], $$[$0], new NodoMM ("LISTADIMS", "LISTADIMS", _$[$0-2], 0)])
        
break;
case 38:

            this.$ = new NodoMM ("PARAM", "PARAM", _$[$0-2], [$$[$0-3], $$[$0-1], $$[$0]])
        
break;
case 39:

            this.$ = new ExpLlamadaFuncion ("LLAMADAFUNCION", "LLAMADAFUNCION", _$[$0-3], [$$[$0-3], $$[$0-1]]);
        
break;
case 40:

            this.$ = new ExpLlamadaFuncion ("LLAMADAFUNCION", "LLAMADAFUNCION", _$[$0-2], [$$[$0-2], new NodoMM ("LISTAEXP", "LISTAEXP", _$[$0-2], [])]);
        
break;
case 41:

            this.$ = new ExpTernario ("TERNARIO","TERNARIO",_$[$0-4],[$$[$0-4], $$[$0-2], $$[$0]]);
        
break;
case 42:

            this.$ = new SentSWITCH ("SWITCH","SWITCH",_$[$0-2],[$$[$0-2],$$[$0]]);
        
break;
case 43:

            this.$ = new SentSWITCH ("SWITCH","BLOQUESWITCH",_$[$0-5],[$$[$0-4],$$[$0-1]]);
        
break;
case 45:

            let nodolistacase = new SentSWITCH ("LISTACASE","LISTACASE",_$[$0],[$$[$0]]);
            this.$ = nodolistacase;
        
break;
case 46:

            this.$ = new SentSWITCH ("CASE","CASE",_$[$0-3],[$$[$0-2],$$[$0]]);
        
break;
case 47:

            this.$ = new SentFOR ("FOR","FOR",_$[$0-8],[$$[$0-6],$$[$0-4],$$[$0-2],$$[$0]]);
        
break;
case 48:

            this.$ = new SentFOR ("FORIN","FORIN",_$[$0-7],[$$[$0-4],$$[$0-2],$$[$0]]);
        
break;
case 49:

            this.$ = new SentFOR ("FOROF","FOROF",_$[$0-7],[$$[$0-4],$$[$0-2],$$[$0]]);
        
break;
case 52:

            this.$ = new SentWHILE ("WHILE","WHILE",_$[$0-4],[$$[$0-2],$$[$0]]);
        
break;
case 53:

            this.$ = new SentDO ("DO","DO",_$[$0-6],[$$[$0-2],$$[$0-5]]);
        
break;
case 54:

            let nodoelse = new SentIF("else","ELSE",_$[$0-1],[$$[$0]]);
            $$[$0-2].hijos.push(nodoelse);
            this.$ = $$[$0-2];
        
break;
case 56:

        let nodoifelse = new SentIF("IFELSE","IFELSE",_$[$0-6],[$$[$0-2],$$[$0]]);
        $$[$0-6].hijos.push(nodoifelse);
        this.$ = $$[$0-6];
    
break;
case 57:

        let nodoif = new SentIF("IF","IF",_$[$0-4],[$$[$0-2],$$[$0]]);
        this.$ = new SentIF("IFMAESTRO","IFMAESTRO",_$[$0-4],[nodoif]);
    
break;
case 58:

            $$[$0-2].hijos = $$[$0-2].hijos+ 1;
            this.$ = $$[$0-2];
        
break;
case 59:

            this.$ = new NodoMM ("LISTADIMS", "LISTADIMS", _$[$0-1], 1);
        
break;
case 60:

            this.$ = new NodoMM("const", "const", _$[$0], []);
        
break;
case 61:

            this.$ = new NodoMM("let", "let", _$[$0], []);
        
break;
case 62:

            this.$ = new Declaracion ("DECLA", "DECLA", _$[$0-1], [$$[$0-1], $$[$0]]);
        
break;
case 64:

            this.$ = new Declaracion ("LISTADECLA", "LISTADECLA", _$[$0], [$$[$0]]);
        
break;
case 65:

            this.$ = new Declaracion ("DECLAARR1", "DECLAELEMENT", _$[$0-5], [$$[$0-5], $$[$0-3], $$[$0-2], $$[$0]]);
        
break;
case 66:

            this.$ = new Declaracion ("DECLAARR2", "DECLAELEMENT", _$[$0-3], [$$[$0-3], $$[$0-1], $$[$0]]);
        
break;
case 67:

            this.$ = new Declaracion ("DECLAVAR1", "DECLAELEMENT", _$[$0-4], [$$[$0-4], $$[$0-2], $$[$0]]);
        
break;
case 68:

            this.$ = new Declaracion ("DECLAVAR2", "DECLAELEMENT", _$[$0-2], [$$[$0-2], $$[$0]]);
        
break;
case 69:

            this.$ = new Declaracion ("DECLAVAR3", "DECLAELEMENT", _$[$0-2], [$$[$0-2], $$[$0]]);
        
break;
case 70:

            this.$ = new Declaracion ("DECLAVAR4", "DECLAELEMENT", _$[$0], [$$[$0]]);
        
break;
case 71:

            this.$ = new DefObj ("DEFOBJ", "DEFOBJ", _$[$0-5], [$$[$0-5], $$[$0-2]]);
        
break;
case 72:

            $$[$0-5].hijos.push(new NodoMM("ATTR", "ATTR", _$[$0-5], [$$[$0-3], $$[$0-1], $$[$0]]));
            this.$ = $$[$0-5];
        
break;
case 73:

            $$[$0-4].hijos.push(new NodoMM("ATTR", "ATTR", _$[$0-4], [$$[$0-2], $$[$0]]));
            this.$ = $$[$0-4];
        
break;
case 74:

            this.$ = new NodoMM("LATTR", "LATTR", _$[$0-3], [
                new NodoMM("ATTR", "ATTR", _$[$0-3], [$$[$0-3], $$[$0-1], $$[$0]])
            ]);
        
break;
case 75:

            this.$ = new NodoMM("LATTR", "LATTR", _$[$0-2], [
                new NodoMM("ATTR", "ATTR", _$[$0-2], [$$[$0-2], $$[$0]])
            ]);
        
break;
case 77:

            $$[$0-4].hijos.push(new NodoMM("ATTRDEF", "ATTRDEF", _$[$0-4], [$$[$0-2], $$[$0]]));
            this.$ = $$[$0-4];
        
break;
case 78:

            this.$ = new ExpObjeto("EXPOBJ", "EXPOBJ", _$[$0-2], [
                new NodoMM("ATTR", "ATTR", _$[$0-2], [$$[$0-2], $$[$0]])
            ]);
        
break;
case 79:

            this.$ = new Asignacion ("ASIGNACION", "ASIGNACION", _$[$0-2], [$$[$0-2], $$[$0]]);
        
break;
case 81:

            this.$ = new Asignacion ("ASIGNACION", "ASIGNACION", _$[$0-1], [
                $$[$0-1], 
                new Expresion ("MAS", "+", _$[$0-1], [$$[$0-1], new Expresion ("NUMERICO", "1", _$[$0-1], [] )])
            ]);
        
break;
case 82:

            this.$ = new Asignacion ("ASIGNACION", "ASIGNACION", _$[$0-1], [
                $$[$0-1], 
                new Expresion ("MENOS", "-", _$[$0-1], [$$[$0-1], new Expresion ("NUMERICO", "1", _$[$0-1], [] )])
            ]);
        
break;
case 83:

            $$[$0-1].hijos = $$[$0-1].hijos.concat($$[$0]);
            this.$ = $$[$0-1];
        
break;
case 84:

            this.$ = new Recursivo ("LLAMADARECURSIVA", "LLAMADARECURSIVA", _$[$0], [$$[$0]]);
        
break;
case 85:

            this.$ = new Recursivo ("LLAMADARECURSIVA", "LLAMADARECURSIVA", _$[$0-1], [$$[$0-1], $$[$0]]);
        
break;
case 86:
   
            this.$ = [$$[$0]];
        
break;
case 87:

            this.$ = [$$[$0-1], $$[$0]];
        
break;
case 88:

            this.$ = [new NodoMM("LENGTH", "LENGTH", _$[$0-1], [])];
        
break;
case 89:

            this.$ = [new NodoMM("POP", "POP", _$[$0-3], [])];
        
break;
case 90:

            this.$ = [new NodoMM("PUSH", "PUSH", _$[$0-4], [$$[$0-1]])];
        
break;
case 91:

            this.$ = [new NodoMM("TOLOWER", "TOLOWER", _$[$0-3], [$$[$0]])];
        
break;
case 92:

            this.$ = [new NodoMM("TOUPPER", "TOUPPER", _$[$0-3], [$$[$0]])];
        
break;
case 93:

            $$[$0-3].hijos.push($$[$0-1]);
            this.$ = $$[$0-3];
        
break;
case 94:

            this.$ = new NodoMM ("LISTAACCESODIMS", "LISTAACCESODIMS",_$[$0-1],[$$[$0-1]]);
        
break;
case 95:

            this.$ = new Imprimir ("imprimir","PRINT",_$[$0-6], [$$[$0-2]]);
        
break;
case 96:

            this.$ = new GraficarTS ("imprimir","PRINT",_$[$0-3], []);
        
break;
case 97:

            this.$ = new Condicional ("AND", "&&", _$[$0-2], [$$[$0-2], $$[$0]]);
        
break;
case 98:

            this.$ = new Condicional ("OR", "||", _$[$0-2], [$$[$0-2], $$[$0]]);
        
break;
case 99:

            this.$ = new Condicional ("NOT", "!", _$[$0-1], [$$[$0]]);
        
break;
case 102:

            this.$ = new Relacional ("MAYOR", ">", _$[$0-2], [$$[$0-2], $$[$0]]);
        
break;
case 103:

            this.$ = new Relacional ("MENOR", "<", _$[$0-2], [$$[$0-2], $$[$0]]);
        
break;
case 104:

            this.$ = new Relacional ("MENOROIGUAL", "<=", _$[$0-2], [$$[$0-2], $$[$0]]);
        
break;
case 105:

            this.$ = new Relacional ("MAYOROIGUAL", ">=", _$[$0-2], [$$[$0-2], $$[$0]]);
        
break;
case 106:

            this.$ = new Relacional ("IGUALIGUAL", "==", _$[$0-2], [$$[$0-2], $$[$0]]);
        
break;
case 107:

            this.$ = new Relacional ("DIFERENTE", "!=", _$[$0-2], [$$[$0-2], $$[$0]]);
        
break;
case 109:

            this.$ = new Expresion ("MAS", "+", _$[$0-2], [$$[$0-2],$$[$0]] );
        
break;
case 110:

            this.$ = new Expresion ("MENOS", "-", _$[$0-2], [$$[$0-2],$$[$0]] );
        
break;
case 111:

            this.$ = new Expresion ("POR", "*", _$[$0-2], [$$[$0-2],$$[$0]] );
        
break;
case 112:

            this.$ = new Expresion ("POTENCIA", "**", _$[$0-2], [$$[$0-2],$$[$0]] );
        
break;
case 113:

            this.$ = new Expresion ("DIV", "/", _$[$0-2], [$$[$0-2],$$[$0]] );
        
break;
case 114:

            this.$ = new Expresion ("MODULO", "%", _$[$0-2], [$$[$0-2],$$[$0]] );
        
break;
case 115:

            this.$ = new Expresion ("NUMERICOE", yytext, _$[$0], [] );
        
break;
case 116:

            this.$ = new Expresion ("NUMERICO", yytext, _$[$0], [] );
        
break;
case 117:

            this.$ = new Expresion ("NEGADO", "-", _$[$0-1], [$$[$0]] );
        
break;
case 118:

            this.$ = new Expresion ("STRING", ((yytext.split("\\\"").join("\"")).split("\\t").join("\t")).split("\\n").join("\n").split("\\\\").join("\\").split("\\r").join("\r"), _$[$0], [] );
        
break;
case 119:

            this.$ = new Expresion ("BOOLEAN", "true", _$[$0], [] );
        
break;
case 120:

            this.$ = new Expresion ("BOOLEAN", "false", _$[$0], [] );
        
break;
case 121:

            this.$ = new Expresion ("NULL", "null", _$[$0], [] );
        
break;
case 122:

            this.$ = new Expresion ("UNDEFINED", "undefined", _$[$0], [] );
        
break;
case 123:

            $$[$0-1].parentesis = true;
            this.$ = $$[$0-1];
        
break;
case 130:

            this.$ = new ExpArrayNew ("EXPARRAYNEW", "EXPARRAYNEW", _$[$0-3], [$$[$0-1]]);
        
break;
case 131:

            this.$ = new ExpArray ("EXPARRAY", "EXPARRAY", _$[$0-1], [$$[$0-1]]);
        
break;
case 132:

            this.$ = new ExpArray ("EXPARRAY", "EXPARRAY", _$[$0], []);
        
break;
case 134:

            this.$ = new NodoMM ("LISTAEXP", "LISTAEXP", _$[$0], [$$[$0]]);
        
break;
case 135:

            this.$ = new NodoMM ("ID", yytext, _$[$0], [] );
        
break;
}
},
table: [{3:1,4:2,6:3,8:4,9:5,10:6,11:7,13:8,14:9,15:10,16:11,17:12,18:13,19:14,20:15,21:16,22:17,23:18,24:19,29:$V0,30:$V1,31:$V2,33:$V3,34:25,45:$V4,51:$V5,53:23,54:$V6,57:$V7,58:$V8,59:27,61:$V9,64:$Va,65:$Vb,69:$Vc,73:24,84:$Vd,86:$Ve},{1:[3]},{5:[1,39],6:40,8:4,9:5,10:6,11:7,13:8,14:9,15:10,16:11,17:12,18:13,19:14,20:15,21:16,22:17,23:18,24:19,29:$V0,30:$V1,31:$V2,33:$V3,34:25,45:$V4,51:$V5,53:23,54:$V6,57:$V7,58:$V8,59:27,61:$V9,64:$Va,65:$Vb,69:$Vc,73:24,84:$Vd,86:$Ve},o($Vf,[2,3]),o($Vf,[2,6]),o($Vf,[2,7]),o($Vg,[2,8]),{12:[1,41]},{12:[1,42]},{12:[1,43],68:$Vh,74:$Vi,75:$Vj,76:45,78:$Vk},o($Vg,[2,12]),o($Vg,[2,13]),o($Vg,[2,14]),o($Vg,[2,15]),o($Vg,[2,16]),o($Vg,[2,17]),o($Vg,[2,18]),o($Vg,[2,19]),o($Vg,[2,20]),{12:[1,49]},{34:50,54:$V6},{78:[1,51]},{35:[1,52]},{34:55,54:$V6,66:53,67:54},o($Vl,[2,80]),o($Vm,$Vn,{77:56,35:[1,57],62:$Vo}),{34:59,54:$V6},o($Vg,[2,55],{60:[1,60]}),{35:[1,61]},{25:62,26:$Vp},{35:[1,64]},{12:[1,65]},{12:[1,66]},{12:[1,67],14:82,24:87,26:$Vq,32:68,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{35:[1,91]},{54:[2,60]},{54:[2,61]},o([12,26,27,35,37,38,40,44,62,63,68,74,75,78,87,88,92,93,94,95,96,97,98,99,100,101,102,103],$VD),{35:[1,92]},{1:[2,1]},o($Vf,[2,2]),o($Vg,[2,9]),o($Vg,[2,10]),o($Vg,[2,11]),{14:82,24:87,26:$Vq,32:93,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},o($Vm,[2,83]),o($VE,[2,81]),o($VE,[2,82]),{34:94,54:$V6,79:[1,95],80:[1,96],81:[1,97],82:[1,98],83:[1,99]},o($Vg,[2,21]),{35:[1,100]},{85:[1,101]},{37:[1,102]},{12:[2,62],40:[1,103]},o($VF,[2,64]),o($VF,[2,70],{38:[1,104],68:[1,105]}),o($Vm,[2,85],{62:$VG}),{14:82,24:87,26:$Vq,32:109,34:25,35:$Vr,37:[1,108],42:107,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,32:110,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{68:[1,111]},{25:112,26:$Vp,61:[1,113]},{14:82,24:87,26:$Vq,32:114,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{57:[1,115]},{7:116,8:118,10:6,11:7,13:8,14:9,15:10,16:11,17:12,18:13,19:14,20:15,21:16,22:17,23:18,24:19,27:[1,117],29:$V0,30:$V1,31:$V2,34:25,45:$V4,51:$V5,53:23,54:$V6,57:$V7,58:$V8,59:27,61:$V9,64:$Va,65:$Vb,69:$Vc,73:24,84:$Vd,86:$Ve},{11:121,13:122,14:123,34:124,52:119,53:120,54:$V6,64:$Va,65:$Vb,73:24},o($Vg,[2,25]),o($Vg,[2,26]),o($Vg,[2,27]),{12:[1,125],44:$VH,87:$VI,88:$VJ},{14:82,24:87,26:$Vq,32:129,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},o($VK,[2,100]),o($VK,[2,101]),o($VK,[2,108],{92:[1,130],93:[1,131],94:[1,132],95:[1,133],96:[1,134],97:[1,135],98:$VL,99:$VM,100:$VN,101:$VO,102:$VP,103:$VQ}),o($VE,[2,115]),o($VE,[2,116]),{14:82,24:87,26:$Vq,34:25,35:$Vr,54:$V6,62:$Vs,71:85,73:86,91:142,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},o($VE,[2,118]),o($VE,[2,119]),o($VE,[2,120]),o($VE,[2,121]),o($VE,[2,122]),{14:82,24:87,26:$Vq,32:143,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},o($VE,[2,124],{76:45,74:$Vi,75:$Vj,78:$Vk}),o($VE,[2,125]),o($VE,[2,126]),o($VE,[2,127]),o($VE,[2,128]),o($VE,[2,129]),{14:82,24:87,26:$Vq,32:109,34:25,35:$Vr,42:144,43:71,54:$V6,62:$Vs,63:[1,145],71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{114:[1,146]},{34:148,54:$V6,72:147},{14:82,24:87,26:$Vq,32:149,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,32:150,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},o($Vl,[2,79],{44:$VH,87:$VI,88:$VJ}),o($Vm,[2,86],{77:151,62:$Vo}),o($Vm,[2,88]),{35:[1,152]},{35:[1,153]},{35:[1,154]},{35:[1,155]},{34:159,36:156,37:[1,157],41:158,54:$V6},{35:[1,160]},{12:[1,161]},{34:55,54:$V6,67:162},{34:163,54:$V6},{14:82,24:87,26:$Vq,32:164,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,32:165,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{37:[1,166],40:$VR},o($VE,[2,40]),o($VS,[2,134],{44:$VH,87:$VI,88:$VJ}),{44:$VH,63:[1,168],87:$VI,88:$VJ},{26:[1,169]},o($Vg,[2,54]),{35:[1,170]},{37:[1,171],44:$VH,87:$VI,88:$VJ},{35:[1,172]},{8:174,10:6,11:7,13:8,14:9,15:10,16:11,17:12,18:13,19:14,20:15,21:16,22:17,23:18,24:19,27:[1,173],29:$V0,30:$V1,31:$V2,34:25,45:$V4,51:$V5,53:23,54:$V6,57:$V7,58:$V8,59:27,61:$V9,64:$Va,65:$Vb,69:$Vc,73:24,84:$Vd,86:$Ve},o($VT,[2,23]),o($VU,[2,5]),{12:[1,175]},{34:55,54:[1,176],66:53,67:54},{12:[2,50]},{12:[2,51]},{68:$Vh,74:$Vi,75:$Vj,76:45,78:$Vk},o([68,74,75,78],$Vn,{77:56,62:$Vo}),o($Vg,[2,28]),{14:82,24:87,26:$Vq,32:177,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,32:178,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,32:179,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},o($VK,[2,99]),{14:82,24:87,26:$Vq,34:25,35:$Vr,54:$V6,62:$Vs,71:85,73:86,91:180,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,34:25,35:$Vr,54:$V6,62:$Vs,71:85,73:86,91:181,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,34:25,35:$Vr,54:$V6,62:$Vs,71:85,73:86,91:182,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,34:25,35:$Vr,54:$V6,62:$Vs,71:85,73:86,91:183,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,34:25,35:$Vr,54:$V6,62:$Vs,71:85,73:86,91:184,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,34:25,35:$Vr,54:$V6,62:$Vs,71:85,73:86,91:185,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,34:25,35:$Vr,54:$V6,62:$Vs,71:85,73:86,91:186,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,34:25,35:$Vr,54:$V6,62:$Vs,71:85,73:86,91:187,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,34:25,35:$Vr,54:$V6,62:$Vs,71:85,73:86,91:188,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,34:25,35:$Vr,54:$V6,62:$Vs,71:85,73:86,91:189,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,34:25,35:$Vr,54:$V6,62:$Vs,71:85,73:86,91:190,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,34:25,35:$Vr,54:$V6,62:$Vs,71:85,73:86,91:191,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},o($VE,[2,117]),{37:[1,192],44:$VH,87:$VI,88:$VJ},{40:$VR,63:[1,193]},o($VE,[2,132]),{35:[1,194]},{27:[1,195],40:[1,196]},{38:[1,197]},{37:[1,198],44:$VH,87:$VI,88:$VJ},{37:[1,199],44:$VH,87:$VI,88:$VJ},o($Vm,[2,87],{62:$VG}),{37:[1,200]},{14:82,24:87,26:$Vq,32:201,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{37:[1,202]},{37:[1,203]},{37:[1,204],40:[1,205]},{26:$VV,28:207,38:[1,206]},o($VW,[2,36]),{38:[1,209]},{14:82,24:87,26:$Vq,32:109,34:25,35:$Vr,42:210,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},o($Vg,[2,96]),o($VF,[2,63]),o($VF,[2,69],{39:211,62:$VX,68:[1,212]}),o($VF,[2,68],{44:$VH,87:$VI,88:$VJ}),{44:$VH,63:[1,214],87:$VI,88:$VJ},o($VE,[2,39]),{14:82,24:87,26:$Vq,32:215,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},o($VY,[2,94]),{34:217,54:$V6,70:216},{14:82,24:87,26:$Vq,32:218,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{25:219,26:$Vp},{14:82,24:87,26:$Vq,32:220,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},o($VT,[2,22]),o($VU,[2,4]),{14:82,24:87,26:$Vq,32:221,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},o([12,38,40,68],$VD,{55:[1,222],56:[1,223]}),o($VK,[2,97]),o([12,27,37,38,40,44,63,88],[2,98],{87:$VI}),{38:[1,224],44:$VH,87:$VI,88:$VJ},o($VK,[2,102],{98:$VL,99:$VM,100:$VN,101:$VO,102:$VP,103:$VQ}),o($VK,[2,103],{98:$VL,99:$VM,100:$VN,101:$VO,102:$VP,103:$VQ}),o($VK,[2,104],{98:$VL,99:$VM,100:$VN,101:$VO,102:$VP,103:$VQ}),o($VK,[2,105],{98:$VL,99:$VM,100:$VN,101:$VO,102:$VP,103:$VQ}),o($VK,[2,106],{98:$VL,99:$VM,100:$VN,101:$VO,102:$VP,103:$VQ}),o($VK,[2,107],{98:$VL,99:$VM,100:$VN,101:$VO,102:$VP,103:$VQ}),o($VZ,[2,109],{100:$VN,101:$VO,102:$VP,103:$VQ}),o($VZ,[2,110],{100:$VN,101:$VO,102:$VP,103:$VQ}),o($V_,[2,111],{101:$VO,103:$VQ}),o($VE,[2,112]),o($V_,[2,113],{101:$VO,103:$VQ}),o($VE,[2,114]),o($VE,[2,123]),o($VE,[2,131]),{14:82,24:87,26:$Vq,32:225,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},o($VE,[2,76]),{34:226,54:$V6},{14:82,24:87,26:$Vq,32:227,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{26:[1,229],46:228},{25:230,26:$Vp},o($Vm,[2,89]),{37:[1,231],44:$VH,87:$VI,88:$VJ},o($Vm,[2,91]),o($Vm,[2,92]),{26:$VV,28:233,38:[1,232]},{34:159,41:234,54:$V6},{34:235,54:$V6},o($Vf,[2,34]),{4:236,6:3,8:4,9:5,10:6,11:7,13:8,14:9,15:10,16:11,17:12,18:13,19:14,20:15,21:16,22:17,23:18,24:19,29:$V0,30:$V1,31:$V2,33:$V3,34:25,45:$V4,51:$V5,53:23,54:$V6,57:$V7,58:$V8,59:27,61:$V9,64:$Va,65:$Vb,69:$Vc,73:24,84:$Vd,86:$Ve},{34:237,54:$V6},{37:[1,238],40:$VR},o($VF,[2,66],{62:$V$,68:[1,239]}),{14:82,24:87,26:$Vq,32:241,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{63:[1,242]},o($VY,[2,93]),o($VS,[2,133],{44:$VH,87:$VI,88:$VJ}),{27:[1,243],40:[1,244]},{38:[1,245]},{37:[1,246],44:$VH,87:$VI,88:$VJ},o($Vg,[2,52]),{37:[1,247],44:$VH,87:$VI,88:$VJ},{12:[1,248],44:$VH,87:$VI,88:$VJ},{14:82,24:87,26:$Vq,32:249,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,32:250,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{14:82,24:87,26:$Vq,32:251,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{37:[1,252],44:$VH,87:$VI,88:$VJ},{38:[1,253]},o($V01,[2,78],{44:$VH,87:$VI,88:$VJ}),o($Vg,[2,42]),{47:254,49:255,50:$V11},o($VT,[2,57]),o($Vm,[2,90]),{34:257,54:$V6},o($Vf,[2,31]),o($VW,[2,35]),{26:$VV,28:259,39:258,62:$VX},{6:40,8:4,9:5,10:6,11:7,13:8,14:9,15:10,16:11,17:12,18:13,19:14,20:15,21:16,22:17,23:18,24:19,27:[1,260],29:$V0,30:$V1,31:$V2,33:$V3,34:25,45:$V4,51:$V5,53:23,54:$V6,57:$V7,58:$V8,59:27,61:$V9,64:$Va,65:$Vb,69:$Vc,73:24,84:$Vd,86:$Ve},o($VW,[2,37],{39:261,62:$VX}),{12:[1,262]},{14:82,24:87,26:$Vq,32:263,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{63:[1,264]},o($VF,[2,67],{44:$VH,87:$VI,88:$VJ}),o($V21,[2,59]),{12:[1,265]},{34:266,54:$V6},{34:267,54:$V6},{25:268,26:$Vp},{12:[1,269]},{13:270,14:123,34:124,54:$V6,73:24},{37:[1,271],44:$VH,87:$VI,88:$VJ},{37:[1,272],44:$VH,87:$VI,88:$VJ},o([12,27,37,38,40,63],[2,41],{44:$VH,87:$VI,88:$VJ}),o($VE,[2,130]),{14:82,24:87,26:$Vq,32:273,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{48:[1,274],49:275,50:$V11},o($V31,[2,45]),{14:82,24:87,26:$Vq,32:276,34:25,35:$Vr,43:71,54:$V6,62:$Vs,71:85,73:86,89:$Vt,90:70,91:72,99:$Vu,104:$Vv,105:$Vw,106:$Vx,107:$Vy,108:$Vz,109:$VA,110:$VB,111:83,112:84,113:$VC},{26:$VV,28:278,39:277,62:$VX},{26:$VV,28:279,62:$V$},o($Vf,[2,33]),o($Vf,[2,24]),o($VW,[2,38],{62:$V$}),o($Vg,[2,95]),o($VF,[2,65],{44:$VH,87:$VI,88:$VJ}),o($V21,[2,58]),o($Vg,[2,71]),{38:[1,280]},o($V01,[2,75],{39:281,62:$VX}),o($VT,[2,56]),o($Vg,[2,53]),{37:[1,282]},{25:283,26:$Vp},{25:284,26:$Vp},o($V01,[2,77],{44:$VH,87:$VI,88:$VJ}),{38:[1,285]},o($V31,[2,44]),{38:[1,286],44:$VH,87:$VI,88:$VJ},{26:$VV,28:287,62:$V$},o($Vf,[2,30]),o($Vf,[2,32]),{34:288,54:$V6},o($V01,[2,74],{62:$V$}),{25:289,26:$Vp},o($Vg,[2,48]),o($Vg,[2,49]),{7:290,8:118,10:6,11:7,13:8,14:9,15:10,16:11,17:12,18:13,19:14,20:15,21:16,22:17,23:18,24:19,29:$V0,30:$V1,31:$V2,34:25,45:$V4,51:$V5,53:23,54:$V6,57:$V7,58:$V8,59:27,61:$V9,64:$Va,65:$Vb,69:$Vc,73:24,84:$Vd,86:$Ve},{7:291,8:118,10:6,11:7,13:8,14:9,15:10,16:11,17:12,18:13,19:14,20:15,21:16,22:17,23:18,24:19,29:$V0,30:$V1,31:$V2,34:25,45:$V4,51:$V5,53:23,54:$V6,57:$V7,58:$V8,59:27,61:$V9,64:$Va,65:$Vb,69:$Vc,73:24,84:$Vd,86:$Ve},o($Vf,[2,29]),o($V01,[2,73],{39:292,62:$VX}),o($Vg,[2,47]),{8:174,10:6,11:7,13:8,14:9,15:10,16:11,17:12,18:13,19:14,20:15,21:16,22:17,23:18,24:19,27:[1,293],29:$V0,30:$V1,31:$V2,34:25,45:$V4,51:$V5,53:23,54:$V6,57:$V7,58:$V8,59:27,61:$V9,64:$Va,65:$Vb,69:$Vc,73:24,84:$Vd,86:$Ve},o($V31,[2,46],{10:6,11:7,13:8,14:9,15:10,16:11,17:12,18:13,19:14,20:15,21:16,22:17,23:18,24:19,53:23,73:24,34:25,59:27,8:174,29:$V0,30:$V1,31:$V2,45:$V4,51:$V5,54:$V6,57:$V7,58:$V8,61:$V9,64:$Va,65:$Vb,69:$Vc,84:$Vd,86:$Ve}),o($V01,[2,72],{62:$V$}),o($Vg,[2,43])],
defaultActions: {35:[2,60],36:[2,61],39:[2,1],121:[2,50],122:[2,51]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        if (hash["token"] == "INVALID") {
            window.errores.push(
              new plantillaError(
                "Lexico",
                "Lexema: " + hash["text"] + ", no reconocido.",
                hash["loc"]["last_line"],
                hash["loc"]["last_column"]
              )
            );
          } else {
            window.errores.push(
              new plantillaError(
                "Sintactico",
                "Error en: " +
                  hash["text"] +
                  ", se esperaba " +
                  hash["expected"] +
                  ".",
                hash["loc"]["last_line"],
                hash["loc"]["last_column"]
              )
            );
          }
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};


  /*
  if (hash["token"] == "INVALID") {
          window.errores.push(
            new plantillaError(
              "Lexico",
              "Lexema: " + hash["text"] + ", no reconocido.",
              hash["loc"]["last_line"],
              hash["loc"]["last_column"]
            )
          );
        } else {
          window.errores.push(
            new plantillaError(
              "Sintactico",
              "Error en: " +
                hash["text"] +
                ", se esperaba " +
                hash["expected"] +
                ".",
              hash["loc"]["last_line"],
              hash["loc"]["last_column"]
            )
          );
        }

   */



parser.treeparser  = {
 raiz : null
};

 parser.error ={
  error:[]

};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"ranges":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespace */;
break;
case 1:/*skip comment*/;
break;
case 2:this.begin('comment');
break;
case 3:this.popState();
break;
case 4:/* skip comment content*/
break;
case 5:/* skip whitespace */
break;
case 6:return 105;
break;
case 7:return 104;
break;
case 8:return 103;
break;
case 9:return 74;
break;
case 10:return 101;
break;
case 11:return 75;
break;
case 12:return 96;
break;
case 13:return 97;
break;
case 14:return 95;
break;
case 15:return 94;
break;
case 16:return 92;
break;
case 17:return 93;
break;
case 18:return 44;
break;
case 19:return 38;
break;
case 20:return 87;
break;
case 21:return 88;
break;
case 22:return 68;
break;
case 23:return 89;
break;
case 24:return 99;
break;
case 25:return 98;
break;
case 26:return 103;
break;
case 27:return 100;
break;
case 28:return 102;
break;
case 29:return 35;
break;
case 30:return 37;
break;
case 31:return 26;
break;
case 32:return 27;
break;
case 33:return 62;
break;
case 34:return 63;
break;
case 35:return 12;
break;
case 36:return 40;
break;
case 37:return 78;
break;
case 38:return 69;
break;
case 39:return 61;
break;
case 40:return 60;
break;
case 41:return 84;
break;
case 42:return 85;
break;
case 43:return 57;
break;
case 44:return 58;
break;
case 45:return 31;
break;
case 46:return 30;
break;
case 47:return 29;
break;
case 48:return 48;
break;
case 49:return 50;
break;
case 50:return 45;
break;
case 51:return 107;
break;
case 52:return 108;
break;
case 53:return 'double';
break;
case 54:return 65;
break;
case 55:return 64;
break;
case 56:return 86;
break;
case 57:return 51;
break;
case 58:return 79;
break;
case 59:return 109;
break;
case 60:return 110;
break;
case 61:return 81;
break;
case 62:return 80;
break;
case 63:return 33;
break;
case 64:return 83;
break;
case 65:return 82;
break;
case 66:return 'concat';
break;
case 67:return 113;
break;
case 68:return 114;
break;
case 69:return 55;
break;
case 70:return 56;
break;
case 71:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2);     return 106;
break;
case 72:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2);     return 106;
break;
case 73:return 54;
break;
case 74:return 5;
break;
case 75:return 'INVALID';
break;
}
},
rules: [/^(?:\s+)/,/^(?:\/\/[^\n]*)/,/^(?:\/\*)/,/^(?:\*\/)/,/^(?:.)/,/^(?:\s+)/,/^(?:[0-9]+(\.[0-9]+))/,/^(?:(0|[0-9]+))/,/^(?:%)/,/^(?:\+\+)/,/^(?:\*\*)/,/^(?:--)/,/^(?:==)/,/^(?:!=)/,/^(?:>=)/,/^(?:<=)/,/^(?:>)/,/^(?:<)/,/^(?:\?)/,/^(?::)/,/^(?:&&)/,/^(?:\|\|)/,/^(?:=)/,/^(?:!)/,/^(?:-)/,/^(?:\+)/,/^(?:%)/,/^(?:\*)/,/^(?:\/)/,/^(?:\()/,/^(?:\))/,/^(?:\{)/,/^(?:\})/,/^(?:\[)/,/^(?:\])/,/^(?:;)/,/^(?:,)/,/^(?:\.)/,/^(?:type\b)/,/^(?:if\b)/,/^(?:else\b)/,/^(?:console\b)/,/^(?:log\b)/,/^(?:while\b)/,/^(?:do\b)/,/^(?:return\b)/,/^(?:continue\b)/,/^(?:break\b)/,/^(?:default\b)/,/^(?:case\b)/,/^(?:switch\b)/,/^(?:true\b)/,/^(?:false\b)/,/^(?:double\b)/,/^(?:let\b)/,/^(?:const\b)/,/^(?:graficar_ts\b)/,/^(?:for\b)/,/^(?:length\b)/,/^(?:null\b)/,/^(?:undefined\b)/,/^(?:push\b)/,/^(?:pop\b)/,/^(?:function\b)/,/^(?:toUpperCase\b)/,/^(?:toLowerCase\b)/,/^(?:concat\b)/,/^(?:new\b)/,/^(?:Array\b)/,/^(?:in\b)/,/^(?:of\b)/,/^(?:"((\\")|[^"])*")/,/^(?:'((\\')|[^'])*')/,/^(?:(ñ|Ñ|_|[a-zA-Z])(ñ|Ñ|[a-zA-Z]|[0-9]|_)*)/,/^(?:$)/,/^(?:.)/],
conditions: {"comment":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75],"inclusive":true},"INITIAL":{"rules":[0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = ejecutor;
exports.Parser = ejecutor.Parser;
exports.parse = function () { return ejecutor.parse.apply(ejecutor, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}
export {ejecutor};